INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_ADA_LOVELACE', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_ADA_LOVELACE', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),

('LEADER_ADA_LOVELACE', 'PUNCH_CARDS'),

('LEADER_ADA_LOVELACE', 'MEMENTO_ADA_LOVELACE_PIANO'),
('LEADER_ADA_LOVELACE', 'MEMENTO_ADA_LOVELACE_NOTE_G'),
('LEADER_ADA_LOVELACE', 'MEMENTO_BENJAMIN_FRANKLIN_BIFOCALS'),
('LEADER_ADA_LOVELACE', 'MEMENTO_BENJAMIN_FRANKLIN_KITE'),
('LEADER_ADA_LOVELACE', 'MEMENTO_HIMIKO_QUEEN_YASAKANI_NO_MAGATAMA');

INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('AdaFastMastery', 'LEADER_ADA_LOVELACE', NULL, 'MEMENTO_ADA_LOVELACE_PIANO', 'MEMENTO_BENJAMIN_FRANKLIN_KITE'),
('AdaCodexRush', 'LEADER_ADA_LOVELACE', NULL, 'MEMENTO_HIMIKO_QUEEN_YASAKANI_NO_MAGATAMA', 'MEMENTO_CATHERINE_EAGLE_BANNER'),
('AdaMasteryYields', 'LEADER_ADA_LOVELACE', NULL, 'MEMENTO_ADA_LOVELACE_NOTE_G', 'MEMENTO_BENJAMIN_FRANKLIN_BIFOCALS'),

('TubmanEspionagePopProd', 'LEADER_HARRIET_TUBMAN', NULL, 'MEMENTO_TUBMAN_LANTERN', 'MEMENTO_ADA_LOVELACE_NOTE_G');
