INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_ADA_LOVELACE', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_ADA_LOVELACE', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),

('LEADER_ADA_LOVELACE', 'PUNCH_CARDS'),

('LEADER_ADA_LOVELACE', 'MEMENTO_ADA_LOVELACE_PIANO'),
('LEADER_ADA_LOVELACE', 'MEMENTO_ADA_LOVELACE_NOTE_G'),
('LEADER_ADA_LOVELACE', 'MEMENTO_BENJAMIN_FRANKLIN_BIFOCALS'),
('LEADER_ADA_LOVELACE', 'MEMENTO_BENJAMIN_FRANKLIN_KITE'),
('LEADER_ADA_LOVELACE', 'MEMENTO_HIMIKO_QUEEN_YASAKANI_NO_MAGATAMA');
