INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_ASHOKA_ALT', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('LEADER_ASHOKA_ALT', 'MEMENTO_FOUNDATION_SLING_BULLET'),

('LEADER_ASHOKA_ALT', 'MEMENTO_ASHOKA_CONQUEROR_CHANDA_MAHASENA'),
('LEADER_ASHOKA_ALT', 'MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA'),
('LEADER_ASHOKA_ALT', 'MEMENTO_ASHOKA_CONQUEROR_LION_CAPITAL'),

('LEADER_HIMIKO_ALT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_HIMIKO_ALT', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),

('LEADER_HIMIKO_ALT', 'MEMENTO_HIMIKO_SHAMAN_YATA_NO_KAGAMI'),
('LEADER_HIMIKO_ALT', 'MEMENTO_HIMIKO_SHAMAN_SAKAKI_BRANCH'),
('LEADER_HIMIKO_ALT', 'MEMENTO_HIMIKO_SHAMAN_KUSANAGI_NO_TSURUGI');

INSERT INTO MementoSetSynergy(MementoTypePrimary, MementoTypeSecondary) VALUES
('MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA', 'MEMENTO_AUGUSTUS_CORONA_CIVICA');

INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('AshokaConqHappinessProd', 'LEADER_ASHOKA_ALT', NULL, 'MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA', 'MEMENTO_ASHOKA_RENOUNCER_DIAMOND_THRONE'),
('AshokaConqWarScienceCulture', 'LEADER_ASHOKA_ALT', NULL, 'MEMENTO_TRUNG_DONG_SON_DRUM', 'MEMENTO_HIMIKO_SHAMAN_YATA_NO_KAGAMI'),
('HimikoShamanCulturePercent', 'LEADER_HIMIKO_ALT', NULL, 'MEMENTO_FOUNDATION_GAME_OF_UR', 'MEMENTO_HATSHEPSUT_URAEUS'),
('HimikoShamanInfiniteCelebration', 'LEADER_HIMIKO_ALT', NULL, 'MEMENTO_RIZAL_OPHTHALMOSCOPE', 'MEMENTO_ASHOKA_RENOUNCER_DIAMOND_THRONE'),
('XerxesKoKCitySpam', 'LEADER_XERXES', 'CIVILIZATION_HAN', 'MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('AshokaRenHappinessYields', 'LEADER_ASHOKA', NULL, 'MEMENTO_ASHOKA_RENOUNCER_CHAKRA', 'MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA'),
('AugustusProductionBoost', 'LEADER_AUGUSTUS', NULL, 'MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA', 'MEMENTO_AUGUSTUS_CLIPEUS_VIRTUTIS'),
('AshokaRenCelebrationYields', 'LEADER_ASHOKA', NULL, 'MEMENTO_FOUNDATION_GARUDA_STATUE', 'MEMENTO_HIMIKO_SHAMAN_YATA_NO_KAGAMI'),
('CharlemagneElephantRushMaurya', 'LEADER_CHARLEMAGNE', 'CIVILIZATION_MAURYA', 'MEMENTO_ASHOKA_CONQUEROR_CHANDA_MAHASENA', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),
('CharlemagneElephantRushKhmer', 'LEADER_CHARLEMAGNE', 'CIVILIZATION_KHMER', 'MEMENTO_ASHOKA_CONQUEROR_CHANDA_MAHASENA', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),
('HatshepsutRiverCityProduction', 'LEADER_HATSHEPSUT', NULL, 'MEMENTO_AUGUSTUS_CLIPEUS_VIRTUTIS', 'MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA'),
('HimikoWaBetterBuildings', 'LEADER_HIMIKO', NULL, 'MEMENTO_HIMIKO_QUEEN_GOLDEN_SEAL_STONE', 'MEMENTO_HIMIKO_SHAMAN_KUSANAGI_NO_TSURUGI'),                                               -- TODO seems shoehorned
('JoseCelebrationYields', 'LEADER_JOSE_RIZAL', NULL, 'MEMENTO_HIMIKO_SHAMAN_YATA_NO_KAGAMI', 'MEMENTO_FOUNDATION_GARUDA_STATUE'),
('PachacutiHappinessOffset', 'LEADER_PACHACUTI', NULL, 'MEMENTO_HIMIKO_SHAMAN_KUSANAGI_NO_TSURUGI', 'MEMENTO_PACHACUTI_TOPAYAURI');



