INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('FriedrichBarCulturalCentres', 'LEADER_FRIEDRICH_ALT', NULL, 'MEMENTO_FRIEDRICH_BAROQUE_FLUTE', 'MEMENTO_HIMIKO_SHAMAN_KUSANAGI_NO_TSURUGI'),
('HimikoShamanBuildingCulture', 'LEADER_HIMIKO_ALT', NULL, 'MEMENTO_HIMIKO_SHAMAN_KUSANAGI_NO_TSURUGI', 'MEMENTO_XERXES_ACHAEMENID_CHALCEDONY_SEAL'),
('XerxesAchUniquesCulture', 'LEADER_XERXES_ALT', NULL, 'MEMENTO_XERXES_ACHAEMENID_CHALCEDONY_SEAL', 'MEMENTO_HIMIKO_SHAMAN_KUSANAGI_NO_TSURUGI');