INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_ASHOKA_ALT', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('LEADER_ASHOKA_ALT', 'MEMENTO_FOUNDATION_SLING_BULLET'),

('LEADER_ASHOKA_ALT', 'MEMENTO_ASHOKA_CONQUEROR_CHANDA_MAHASENA'),
('LEADER_ASHOKA_ALT', 'MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA'),
('LEADER_ASHOKA_ALT', 'MEMENTO_ASHOKA_CONQUEROR_LION_CAPITAL'),

('LEADER_HIMIKO_ALT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_HIMIKO_ALT', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),

('LEADER_HIMIKO_ALT', 'MEMENTO_HIMIKO_SHAMAN_YATA_NO_KAGAMI'),
('LEADER_HIMIKO_ALT', 'MEMENTO_HIMIKO_SHAMAN_SAKAKI_BRANCH'),
('LEADER_HIMIKO_ALT', 'MEMENTO_HIMIKO_SHAMAN_KUSANAGI_NO_TSURUGI');

INSERT INTO MementoSetSynergy(MementoTypePrimary, MementoTypeSecondary) VALUES
('MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA', 'MEMENTO_AUGUSTUS_CORONA_CIVICA');

INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('XerxesKoKCitySpam', 'LEADER_XERXES', 'CIVILIZATION_HAN', 'MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA', 'MEMENTO_AUGUSTUS_CORONA_CIVICA');
