INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('BolivarLibertyRush', 'LEADER_BOLIVAR', NULL, 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),
('TrungTracSisterNations', 'LEADER_TRUNG_TRAC', NULL, 'MEMENTO_BOLIVAR_GOLD_SNUFF_BOX', 'MEMENTO_BENJAMIN_FRANKLIN_GLASS_ARMONICA');