INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_BOLIVAR', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_BOLIVAR', 'MEMENTO_FOUNDATION_GROMA'),

('LEADER_BOLIVAR', 'MEMENTO_BOLIVAR_GOLD_SNUFF_BOX'),
('LEADER_BOLIVAR', 'MEMENTO_BOLIVAR_DAVALOS_MEDAL'),
('LEADER_BOLIVAR', 'MEMENTO_BOLIVAR_LETTER_TO_JAMAICA');