INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_BOLIVAR', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_BOLIVAR', 'MEMENTO_FOUNDATION_GROMA'),

('LEADER_BOLIVAR', 'MEMENTO_BOLIVAR_GOLD_SNUFF_BOX'),
('LEADER_BOLIVAR', 'MEMENTO_BOLIVAR_DAVALOS_MEDAL'),
('LEADER_BOLIVAR', 'MEMENTO_BOLIVAR_LETTER_TO_JAMAICA');

INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('CharlemagneHappinessSources', 'LEADER_CHARLEMAGNE', NULL, 'MEMENTO_BOLIVAR_DAVALOS_MEDAL', 'MEMENTO_CHARLEMAGNE_JOYEUSE'),
('BolivarRevolutionaryWar', 'LEADER_BOLIVAR', NULL, 'MEMENTO_BOLIVAR_LETTER_TO_JAMAICA', 'MEMENTO_RIZAL_OPHTHALMOSCOPE');