INSERT INTO CivMementoSynergy(CivilizationType, MementoType) VALUES
('CIVILIZATION_BULGARIA', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('CIVILIZATION_BULGARIA', 'MEMENTO_FOUNDATION_GROMA'),
('CIVILIZATION_BULGARIA', 'MEMENTO_CHARLEMAGNE_JOYEUSE'),
('CIVILIZATION_BULGARIA', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),
('CIVILIZATION_BULGARIA', 'MEMENTO_CATHERINE_POTEMKINS_SWORD_KNOT');