INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_NAPOLEON_ALT', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_NAPOLEON_ALT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),

('LEADER_NAPOLEON_ALT', 'MEMENTO_NAPOLEON_REVOLUTIONARY_ARTILLERYMAN_GLOVES'),
('LEADER_NAPOLEON_ALT', 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT'),
('LEADER_NAPOLEON_ALT', 'MEMENTO_NAPOLEON_REVOLUTIONARY_LEGION_DHONNEUR_GRAND_EAGLE_CROSS');

INSERT INTO CivMementoSynergy(CivilizationType, MementoType) VALUES
('CIVILIZATION_PERSIA', 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT'),
('CIVILIZATION_ROME', 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT');

INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('NapoleonRevFastLandUnits', 'LEADER_NAPOLEON_ALT', NULL, 'MEMENTO_FOUNDATION_AGINCOURT_ARROWHEAD', 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT'),
('NapoleonRevFastNonCombat', 'LEADER_NAPOLEON_ALT', NULL, 'MEMENTO_BATTUTA_MERCHANTS_SADDLE', 'MEMENTO_CATHERINE_POTEMKINS_SWORD_KNOT'),
('FriedrichObTacticalCommanders', 'LEADER_FRIEDRICH', NULL, 'MEMENTO_NAPOLEON_REVOLUTIONARY_LEGION_DHONNEUR_GRAND_EAGLE_CROSS', 'MEMENTO_CATHERINE_POTEMKINS_SWORD_KNOT'),
('FriedrichObMilitaryScience', 'LEADER_FRIEDRICH', NULL, 'MEMENTO_FRIEDRICH_OBLIQUE_WALKING_STICK', 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT'),
('TrungTracCommanderYields', 'LEADER_TRUNG_TRAC', NULL, 'MEMENTO_NAPOLEON_REVOLUTIONARY_ARTILLERYMAN_GLOVES', 'MEMENTO_TRUNG_KIEM');
