INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_NAPOLEON', 'MEMENTO_FOUNDATION_EA_NASIR'),
('LEADER_NAPOLEON', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),

('LEADER_NAPOLEON', 'MEMENTO_NAPOLEON_EMPEROR_PORTRAIT_JOSEPHINE'),
('LEADER_NAPOLEON', 'MEMENTO_NAPOLEON_EMPEROR_GREEN_COLONEL_JACKET'),
('LEADER_NAPOLEON', 'MEMENTO_NAPOLEON_EMPEROR_CROWN_OF_NAPOLEON');               -- cool but maybe not fair