INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_NAPOLEON_ALT', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_NAPOLEON_ALT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),

('LEADER_NAPOLEON_ALT', 'MEMENTO_NAPOLEON_REVOLUTIONARY_ARTILLERYMAN_GLOVES'),
-- ('LEADER_NAPOLEON_ALT', 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT'),                  -- no reason to get infantry unit movement
('LEADER_NAPOLEON_ALT', 'MEMENTO_NAPOLEON_REVOLUTIONARY_LEGION_DHONNEUR_GRAND_EAGLE_CROSS');