INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_NAPOLEON', 'MEMENTO_FOUNDATION_EA_NASIR'),
('LEADER_NAPOLEON', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),

('LEADER_NAPOLEON', 'MEMENTO_NAPOLEON_EMPEROR_PORTRAIT_JOSEPHINE'),
('LEADER_NAPOLEON', 'MEMENTO_NAPOLEON_EMPEROR_GREEN_COLONEL_JACKET'),
('LEADER_NAPOLEON', 'MEMENTO_NAPOLEON_EMPEROR_CROWN_OF_NAPOLEON');               -- cool but maybe not fair

INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('NapoleonEmpSanctionSpammer', 'LEADER_NAPOLEON', NULL, 'MEMENTO_MACHIAVELLI_DISCORSI_SOPRA_LIVIO', 'MEMENTO_MACHIAVELLI_DELL_ARTE_DELLA_GUERRA'),
('NapoleonEmpTaxEnemies', 'LEADER_NAPOLEON', NULL, 'MEMENTO_NAPOLEON_EMPEROR_PORTRAIT_JOSEPHINE', 'MEMENTO_NAPOLEON_EMPEROR_CROWN_OF_NAPOLEON'),
('NapoleonEmpContinentalEnemy', 'LEADER_NAPOLEON', NULL, 'MEMENTO_NAPOLEON_EMPEROR_PORTRAIT_JOSEPHINE', 'MEMENTO_MACHIAVELLI_IL_PRINCIPE'),
('HimikoWaLoveScienceHateGold', 'LEADER_HIMIKO', NULL, 'MEMENTO_BENJAMIN_FRANKLIN_GLASS_ARMONICA', 'MEMENTO_NAPOLEON_EMPEROR_PORTRAIT_JOSEPHINE'),
('MachiavelliGetYourWay', 'LEADER_MACHIAVELLI', NULL, 'MEMENTO_MACHIAVELLI_DISCORSI_SOPRA_LIVIO', 'MEMENTO_NAPOLEON_EMPEROR_PORTRAIT_JOSEPHINE'),
('MachiavelliCashInjection', 'LEADER_MACHIAVELLI', NULL, 'MEMENTO_FOUNDATION_LYDIAN_LION', 'MEMENTO_NAPOLEON_EMPEROR_CROWN_OF_NAPOLEON');