INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_TECUMSEH', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_TECUMSEH', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('LEADER_TECUMSEH', 'MEMENTO_TECUMSEH_POTESKWATE'),
('LEADER_TECUMSEH', 'MEMENTO_TECUMSEH_WARCLUB'),
('LEADER_TECUMSEH', 'MEMENTO_TECUMSEH_WAMPUM_BELT');

INSERT INTO CivMementoSynergy (CivilizationType, MementoType) VALUES
('CIVILIZATION_SHAWNEE', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('CIVILIZATION_SHAWNEE', 'MEMENTO_FOUNDATION_EA_NASIR'),
--
('CIVILIZATION_SHAWNEE', 'MEMENTO_TECUMSEH_POTESKWATE'),
('CIVILIZATION_SHAWNEE', 'MEMENTO_TECUMSEH_WARCLUB'),
('CIVILIZATION_SHAWNEE', 'MEMENTO_TECUMSEH_WAMPUM_BELT'),
('CIVILIZATION_GREECE', 'MEMENTO_TECUMSEH_POTESKWATE'),
('CIVILIZATION_GREECE', 'MEMENTO_TECUMSEH_WARCLUB'),
('CIVILIZATION_GREECE', 'MEMENTO_TECUMSEH_WAMPUM_BELT');

INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('TecumsehUnitedTribes', 'LEADER_TECUMSEH', NULL, 'MEMENTO_TECUMSEH_WAMPUM_BELT', 'MEMENTO_TECUMSEH_POTESKWATE'),
('TecumsehIronConfederacy', 'LEADER_TECUMSEH', NULL, 'MEMENTO_TECUMSEH_WAMPUM_BELT', 'MEMENTO_TECUMSEH_WARCLUB'),
('MachiavelliWorldSuzerain', 'LEADER_MACHIAVELLI', NULL, 'MEMENTO_TECUMSEH_WARCLUB', 'MEMENTO_TECUMSEH_WAMPUM_BELT');
