INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_FRIEDRICH_ALT', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_FRIEDRICH_ALT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),

('LEADER_FRIEDRICH_ALT', 'MEMENTO_FRIEDRICH_BAROQUE_FLUTE'),
('LEADER_FRIEDRICH_ALT', 'MEMENTO_FRIEDRICH_BAROQUE_ANTI_MACHIAVEL'),

--
('LEADER_XERXES_ALT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_XERXES_ALT', 'MEMENTO_FOUNDATION_EA_NASIR'),
('LEADER_XERXES_ALT', 'MEMENTO_FOUNDATION_POCHTECA_BACKPACK'),

('LEADER_XERXES_ALT', 'MEMENTO_XERXES_ACHAEMENID_INCENSE_CENSER'),
('LEADER_XERXES_ALT', 'MEMENTO_XERXES_ACHAEMENID_GOLD_FLUTED_PHIALE'),
('LEADER_XERXES_ALT', 'MEMENTO_XERXES_ACHAEMENID_CHALCEDONY_SEAL');

INSERT INTO MementoSetSynergy(MementoTypePrimary, MementoTypeSecondary) VALUES
('MEMENTO_FOUNDATION_SHAKOKIDOGU', 'MEMENTO_FRIEDRICH_BAROQUE_VOLTAIRE_EDITS');