INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_FRIEDRICH_ALT', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_FRIEDRICH_ALT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),

('LEADER_FRIEDRICH_ALT', 'MEMENTO_FRIEDRICH_BAROQUE_FLUTE'),
('LEADER_FRIEDRICH_ALT', 'MEMENTO_FRIEDRICH_BAROQUE_ANTI_MACHIAVEL'),

--
('LEADER_XERXES_ALT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_XERXES_ALT', 'MEMENTO_FOUNDATION_EA_NASIR'),
('LEADER_XERXES_ALT', 'MEMENTO_FOUNDATION_POCHTECA_BACKPACK'),

('LEADER_XERXES_ALT', 'MEMENTO_XERXES_ACHAEMENID_INCENSE_CENSER'),
('LEADER_XERXES_ALT', 'MEMENTO_XERXES_ACHAEMENID_GOLD_FLUTED_PHIALE'),
('LEADER_XERXES_ALT', 'MEMENTO_XERXES_ACHAEMENID_CHALCEDONY_SEAL');

INSERT INTO MementoSetSynergy(MementoTypePrimary, MementoTypeSecondary) VALUES
('MEMENTO_FOUNDATION_SHAKOKIDOGU', 'MEMENTO_FRIEDRICH_BAROQUE_VOLTAIRE_EDITS');

INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('FriedrichBarMilitaryAcademies', 'LEADER_FRIEDRICH_ALT', NULL, 'MEMENTO_FRIEDRICH_BAROQUE_FLUTE', 'MEMENTO_FRIEDRICH_OBLIQUE_WALKING_STICK'),
('FriedrichBarSpoilsOfWar', 'LEADER_FRIEDRICH_ALT', NULL, 'MEMENTO_CATHERINE_EAGLE_BANNER', 'MEMENTO_HATSHEPSUT_URAEUS'),                       -- third needed himiko alt
('XerxesAchInfiniteTrades', 'LEADER_XERXES_ALT', NULL, 'MEMENTO_XERXES_ACHAEMENID_GOLD_FLUTED_PHIALE', 'MEMENTO_FOUNDATION_POCHTECA_BACKPACK'),
('XerxesAchStrongTrades', 'LEADER_XERXES_ALT', NULL, 'MEMENTO_NAPOLEON_EMPEROR_GREEN_COLONEL_JACKET', 'MEMENTO_XERXES_ACHAEMENID_INCENSE_CENSER'),
('TubmanGuerillaFighter', 'LEADER_HARRIET_TUBMAN', NULL, 'MEMENTO_FRIEDRICH_BAROQUE_ANTI_MACHIAVEL', 'MEMENTO_TRUNG_ANKUS'),
('HatshepsutNileTrade', 'LEADER_HATSHEPSUT', NULL, 'MEMENTO_XERXES_ACHAEMENID_GOLD_FLUTED_PHIALE', 'MEMENTO_XERXES_ACHAEMENID_INCENSE_CENSER'),     -- TODO, is this related to egypt?


('ConfuciusHanBoost', 'LEADER_CONFUCIUS', 'CIVILIZATION_HAN', 'MEMENTO_HIMIKO_QUEEN_GOLDEN_SEAL_STONE', 'MEMENTO_XERXES_ACHAEMENID_CHALCEDONY_SEAL');
