-- trait attribute assignments

INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_AMINA', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_CHARLEMAGNE', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_FRIEDRICH', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_HARRIET_TUBMAN', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_TRUNG_TRAC', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('LEADER_XERXES', 'MEMENTO_FOUNDATION_SLING_BULLET'),

('LEADER_AMINA', 'MEMENTO_FOUNDATION_EA_NASIR'),
('LEADER_HATSHEPSUT', 'MEMENTO_FOUNDATION_EA_NASIR'),
('LEADER_ISABELLA', 'MEMENTO_FOUNDATION_EA_NASIR'),
('LEADER_MACHIAVELLI', 'MEMENTO_FOUNDATION_EA_NASIR'),
('LEADER_PACHACUTI', 'MEMENTO_FOUNDATION_EA_NASIR'),
('LEADER_XERXES', 'MEMENTO_FOUNDATION_EA_NASIR'),

('LEADER_ASHOKA', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('LEADER_HARRIET_TUBMAN', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('LEADER_HIMIKO', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('LEADER_JOSE_RIZAL', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('LEADER_LAFAYETTE', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('LEADER_MACHIAVELLI', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),

('LEADER_ASHOKA', 'MEMENTO_FOUNDATION_GROMA'),
('LEADER_AUGUSTUS', 'MEMENTO_FOUNDATION_GROMA'),
('LEADER_CONFUCIUS', 'MEMENTO_FOUNDATION_GROMA'),
('LEADER_IBN_BATTUTA', 'MEMENTO_FOUNDATION_GROMA'),
('LEADER_ISABELLA', 'MEMENTO_FOUNDATION_GROMA'),
('LEADER_PACHACUTI', 'MEMENTO_FOUNDATION_GROMA'),

('LEADER_AUGUSTUS', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_CATHERINE', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_HATSHEPSUT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_JOSE_RIZAL', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('LEADER_LAFAYETTE', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),

('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('LEADER_CATHERINE', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('LEADER_CHARLEMAGNE', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('LEADER_CONFUCIUS', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('LEADER_FRIEDRICH', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('LEADER_HIMIKO', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('LEADER_TRUNG_TRAC', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM');

-- other military specifics
INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_AMINA', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_CHARLEMAGNE', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_FRIEDRICH', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_HARRIET_TUBMAN', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_TRUNG_TRAC', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_XERXES', 'MEMENTO_AUGUSTUS_CORONA_CIVICA');

-- leader specifics
INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_AUGUSTUS', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_AUGUSTUS', 'MEMENTO_AUGUSTUS_BREASTPLATE'),
('LEADER_AUGUSTUS', 'MEMENTO_AUGUSTUS_CLIPEUS_VIRTUTIS'),

('LEADER_HAPSHETSUT', 'ROYAL_MACE'),
('LEADER_HAPSHETSUT', 'False Beard'),
('LEADER_HAPSHETSUT', 'URUAEUS'),

('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_BENJAMIN_FRANKLIN_BIFOCALS'),
('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_BENJAMIN_FRANKLIN_KITE'),
('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_BENJAMIN_FRANKLIN_GLASS_ARMONICA'),

('LEADER_CATHERINE', 'MEMENTO_CATHERINE_EAGLE_BANNER'),
-- ('LEADER_CATHERINE', 'MEMENTO_CATHERINE_POTEMKINS_SWORD_KNOT'),
('LEADER_CATHERINE', 'MEMENTO_CATHERINE_GREAT_IMPERIAL_CROWN'),

('LEADER_CHARLEMAGNE', 'MEMENTO_CHARLEMAGNE_JOYEUSE'),
-- ('LEADER_CHARLEMAGNE', 'MEMENTO_CHARLEMAGNE_GLOBUS_CRUCIGER'),
('LEADER_CHARLEMAGNE', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),

('LEADER_CONFUCIUS', 'MEMENTO_CONFUCIUS_ANALECTS'),
('LEADER_CONFUCIUS', 'MEMENTO_CONFUCIUS_ALTAR_SET'),
('LEADER_CONFUCIUS', 'MEMENTO_CONFUCIUS_BRUSH_SCROLL'),

('LEADER_ASHOKA', 'MEMENTO_ASHOKA_RENOUNCER_CHAKRA'),
('LEADER_ASHOKA', 'MEMENTO_ASHOKA_RENOUNCER_GOLD_SAPPHIRE_FLOWERS'),
('LEADER_ASHOKA', 'MEMENTO_ASHOKA_RENOUNCER_DIAMOND_THRONE'),

('LEADER_FRIEDRICH', 'MEMENTO_FRIEDRICH_OBLIQUE_WALKING_STICK'),
-- ('LEADER_FRIEDRICH', 'MEMENTO_FRIEDRICH_OBLIQUE_ORDER_BLACK_EAGLE'),             -- already granted
-- ('LEADER_FRIEDRICH', 'MEMENTO_FRIEDRICH_OBLIQUE_KRONE_VON_FRIEDRICH'),           -- ai dont do commands, right

('LEADER_HARRIET_TUBMAN', 'MEMENTO_TUBMAN_LANTERN'),
-- ('LEADER_HARRIET_TUBMAN', 'MEMENTO_TUBMAN_SATCHEL'),
('LEADER_HARRIET_TUBMAN', 'MEMENTO_TUBMAN_SIDEARM'),

('LEADER_AMINA', 'MEMENTO_AMINA_TAKOBA'),
('LEADER_AMINA', 'MEMENTO_AMINA_KWALKWALI'),
('LEADER_AMINA', 'MEMENTO_AMINA_RAWANI'),


('LEADER_HIMIKO', 'MEMENTO_HIMIKO_QUEEN_GOLDEN_SEAL_STONE'),
-- ('LEADER_HIMIKO', 'MEMENTO_HIMIKO_QUEEN_DOTAKU'),         -- science one already granted
('LEADER_HIMIKO', 'MEMENTO_HIMIKO_QUEEN_YASAKANI_NO_MAGATAMA'),

('LEADER_IBN_BATTUTA', 'MEMENTO_BATTUTA_TRAVELLERS_SANDALS'),
('LEADER_IBN_BATTUTA', 'MEMENTO_BATTUTA_MERCHANTS_SADDLE'),
('LEADER_IBN_BATTUTA', 'MEMENTO_BATTUTA_RIHLA'),

('LEADER_ISABELLA', 'MEMENTO_ISABELLA_QUEENS_JEWELRY'),
('LEADER_ISABELLA', 'MEMENTO_ISABELLA_BALLESTILLA'),
('LEADER_ISABELLA', 'MEMENTO_ISABELLA_PADRON_REAL'),

('LEADER_JOSE_RIZAL', 'MEMENTO_RIZAL_FORGET_ME_NOT'),
('LEADER_JOSE_RIZAL', 'MEMENTO_RIZAL_OPHTHALMOSCOPE'),
('LEADER_JOSE_RIZAL', 'MEMENTO_RIZAL_NOLI_ME_TANGERE'),

('LEADER_LAFAYETTE', 'MEMENTO_LAFAYETTE_LETTER_ADRIENNE'),
-- ('LEADER_LAFAYETTE', 'MEMENTO_LAFAYETTE_HERMIONE_MODEL'),                      -- doesnt really suit em
('LEADER_LAFAYETTE', 'MEMENTO_LAFAYETTE_TRICOLOUR_COCKADE'),

('LEADER_MACHIAVELLI', 'MEMENTO_MACHIAVELLI_DISCORSI_SOPRA_LIVIO'),
('LEADER_MACHIAVELLI', 'MEMENTO_MACHIAVELLI_DELL_ARTE_DELLA_GUERRA'),
-- ('LEADER_MACHIAVELLI', 'MEMENTO_MACHIAVELLI_IL_PRINCIPE'),                          -- ai really wont know to use this, also doesnt suit macheveli at all

('LEADER_PACHACUTI', 'MEMENTO_PACHACUTI_TOPAYAURI'),
('LEADER_PACHACUTI', 'MEMENTO_PACHACUTI_ALL_TOQAPU_TUNIC'),                       -- scout increased vision seems rather weak
('LEADER_PACHACUTI', 'MEMENTO_PACHACUTI_MASCAPAYCHA'),

('LEADER_TRUNG_TRAC', 'MEMENTO_TRUNG_KIEM'),
('LEADER_TRUNG_TRAC', 'MEMENTO_TRUNG_ANKUS'),
('LEADER_TRUNG_TRAC', 'MEMENTO_TRUNG_DONG_SON_DRUM'),

('LEADER_XERXES', 'MEMENTO_XERXES_KING_SCYTHIAN_AXE'),
('LEADER_XERXES', 'MEMENTO_XERXES_KING_LOTUS_BLOSSOM'),
('LEADER_XERXES', 'MEMENTO_XERXES_KING_GOLDEN_SCEPTRE');

-- ibn missing wildcard

INSERT INTO CivMementoSynergy(CivilizationType, MementoType) VALUES
('CIVILIZATION_MAURYA', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('CIVILIZATION_PERSIA', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('CIVILIZATION_ROME', 'MEMENTO_FOUNDATION_SLING_BULLET'),

('CIVILIZATION_AKSUM', 'MEMENTO_FOUNDATION_EA_NASIR'),
('CIVILIZATION_EGYPT', 'MEMENTO_FOUNDATION_EA_NASIR'),
('CIVILIZATION_MISSISSIPPIAN', 'MEMENTO_FOUNDATION_EA_NASIR'),
('CIVILIZATION_PERSIA', 'MEMENTO_FOUNDATION_EA_NASIR'),

('CIVILIZATION_GREECE', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('CIVILIZATION_HAN', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('CIVILIZATION_MAYA', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),

('CIVILIZATION_KHMER', 'MEMENTO_FOUNDATION_GROMA'),
('CIVILIZATION_MISSISSIPPIAN', 'MEMENTO_FOUNDATION_GROMA'),

('CIVILIZATION_AKSUM', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('CIVILIZATION_EGYPT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('CIVILIZATION_GREECE', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('CIVILIZATION_ROME', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),

('CIVILIZATION_HAN', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('CIVILIZATION_KHMER', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('CIVILIZATION_MAURYA', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('CIVILIZATION_MAYA', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),

-- buff civs with UUs
('CIVILIZATION_NORMAN', 'MEMENTO_CHARLEMAGNE_JOYEUSE'),
('CIVILIZATION_NORMAN', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),

('CIVILIZATION_MONGOLIA', 'MEMENTO_CHARLEMAGNE_JOYEUSE'),
('CIVILIZATION_MONGOLIA', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),
('CIVILIZATION_MONGOLIA', 'MEMENTO_CATHERINE_POTEMKINS_SWORD_KNOT'),

('CIVILIZATION_CHOLA', 'MEMENTO_LAFAYETTE_HERMIONE_MODEL'),
('CIVILIZATION_MAJAPAHIT', 'MEMENTO_LAFAYETTE_HERMIONE_MODEL'),

('CIVILIZATION_MISSISSIPPIAN', 'MEMENTO_FOUNDATION_AGINCOURT_ARROWHEAD'),
('CIVILIZATION_PERSIA', 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT'),
('CIVILIZATION_ROME', 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT');

-------------------------------------------------

-- bifocals influence diplo

-- unique units with ranged MEMENTO_FOUNDATION_AGINCOURT_ARROWHEAD

-- specialist improving ones


INSERT INTO MementoSetSynergy(MementoTypePrimary, MementoTypeSecondary) VALUES
('MEMENTO_FOUNDATION_SLING_BULLET', 'MEMENTO_FRIEDRICH_OBLIQUE_ORDER_BLACK_EAGLE'),
('MEMENTO_FOUNDATION_TREATY_OF_KADESH', 'MEMENTO_CHARLEMAGNE_GLOBUS_CRUCIGER'),
('MEMENTO_FOUNDATION_GROMA', 'MEMENTO_ASHOKA_RENOUNCER_GOLD_SAPPHIRE_FLOWERS'),
('MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM', 'MEMENTO_HIMIKO_QUEEN_DOTAKU'),
-- non-attribute ones
('MEMENTO_CHARLEMAGNE_JOYEUSE', 'MEMENTO_CHARLEMAGNE_TENCENDUR');


INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('TrungTracRomeLegatus', 'LEADER_TRUNG_TRAC', 'CIVILIZATION_ROME', 'MEMENTO_XERXES_KING_SCYTHIAN_AXE', 'MEMENTO_FOUNDATION_ART_OF_WAR');
