-- trait attribute assignments

INSERT INTO LeaderMementoSynergy (LeaderType, MementoType, AgeType) VALUES
('LEADER_AMINA', 'MEMENTO_FOUNDATION_SLING_BULLET', 'AGE_ANTIQUITY'),
('LEADER_CHARLEMAGNE', 'MEMENTO_FOUNDATION_SLING_BULLET', 'AGE_ANTIQUITY'),
('LEADER_FRIEDRICH', 'MEMENTO_FOUNDATION_SLING_BULLET', 'AGE_ANTIQUITY'),
('LEADER_HARRIET_TUBMAN', 'MEMENTO_FOUNDATION_SLING_BULLET', 'AGE_ANTIQUITY'),
('LEADER_TRUNG_TRAC', 'MEMENTO_FOUNDATION_SLING_BULLET', 'AGE_ANTIQUITY'),
('LEADER_XERXES', 'MEMENTO_FOUNDATION_SLING_BULLET', 'AGE_ANTIQUITY'),

('LEADER_AMINA', 'MEMENTO_FOUNDATION_EA_NASIR', 'AGE_ANTIQUITY'),
('LEADER_HATSHEPSUT', 'MEMENTO_FOUNDATION_EA_NASIR', 'AGE_ANTIQUITY'),
('LEADER_ISABELLA', 'MEMENTO_FOUNDATION_EA_NASIR', 'AGE_ANTIQUITY'),
('LEADER_MACHIAVELLI', 'MEMENTO_FOUNDATION_EA_NASIR', 'AGE_ANTIQUITY'),
('LEADER_PACHACUTI', 'MEMENTO_FOUNDATION_EA_NASIR', 'AGE_ANTIQUITY'),
('LEADER_XERXES', 'MEMENTO_FOUNDATION_EA_NASIR', 'AGE_ANTIQUITY'),

('LEADER_ASHOKA', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH', 'AGE_ANTIQUITY'),
('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH', 'AGE_ANTIQUITY'),
('LEADER_HARRIET_TUBMAN', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH', 'AGE_ANTIQUITY'),
('LEADER_HIMIKO', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH', 'AGE_ANTIQUITY'),
('LEADER_JOSE_RIZAL', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH', 'AGE_ANTIQUITY'),
('LEADER_LAFAYETTE', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH', 'AGE_ANTIQUITY'),
('LEADER_MACHIAVELLI', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH', 'AGE_ANTIQUITY'),

('LEADER_ASHOKA', 'MEMENTO_FOUNDATION_GROMA', 'AGE_ANTIQUITY'),
('LEADER_AUGUSTUS', 'MEMENTO_FOUNDATION_GROMA', 'AGE_ANTIQUITY'),
('LEADER_CONFUCIUS', 'MEMENTO_FOUNDATION_GROMA', 'AGE_ANTIQUITY'),
('LEADER_IBN_BATTUTA', 'MEMENTO_FOUNDATION_GROMA', 'AGE_ANTIQUITY'),
('LEADER_ISABELLA', 'MEMENTO_FOUNDATION_GROMA', 'AGE_ANTIQUITY'),
('LEADER_PACHACUTI', 'MEMENTO_FOUNDATION_GROMA', 'AGE_ANTIQUITY'),

('LEADER_AUGUSTUS', 'MEMENTO_FOUNDATION_SHAKOKIDOGU', 'AGE_ANTIQUITY'),
('LEADER_CATHERINE', 'MEMENTO_FOUNDATION_SHAKOKIDOGU', 'AGE_ANTIQUITY'),
('LEADER_HATSHEPSUT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU', 'AGE_ANTIQUITY'),
('LEADER_JOSE_RIZAL', 'MEMENTO_FOUNDATION_SHAKOKIDOGU', 'AGE_ANTIQUITY'),
('LEADER_LAFAYETTE', 'MEMENTO_FOUNDATION_SHAKOKIDOGU', 'AGE_ANTIQUITY'),

('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM', 'AGE_ANTIQUITY'),
('LEADER_CATHERINE', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM', 'AGE_ANTIQUITY'),
('LEADER_CHARLEMAGNE', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM', 'AGE_ANTIQUITY'),
('LEADER_CONFUCIUS', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM', 'AGE_ANTIQUITY'),
('LEADER_FRIEDRICH', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM', 'AGE_ANTIQUITY'),
('LEADER_HIMIKO', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM', 'AGE_ANTIQUITY'),
('LEADER_TRUNG_TRAC', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM', 'AGE_ANTIQUITY');

-- other military specifics
INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_AMINA', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_CHARLEMAGNE', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_FRIEDRICH', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_HARRIET_TUBMAN', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_TRUNG_TRAC', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_XERXES', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),

('LEADER_AMINA', 'MEMENTO_FOUNDATION_COLADA_TIZONA'),
('LEADER_CHARLEMAGNE', 'MEMENTO_FOUNDATION_COLADA_TIZONA'),
('LEADER_FRIEDRICH', 'MEMENTO_FOUNDATION_COLADA_TIZONA'),
('LEADER_HARRIET_TUBMAN', 'MEMENTO_FOUNDATION_COLADA_TIZONA'),
('LEADER_TRUNG_TRAC', 'MEMENTO_FOUNDATION_COLADA_TIZONA'),
('LEADER_XERXES', 'MEMENTO_FOUNDATION_COLADA_TIZONA'),

('LEADER_AMINA', 'MEMENTO_TUBMAN_SIDEARM'),
('LEADER_CHARLEMAGNE', 'MEMENTO_TUBMAN_SIDEARM'),
('LEADER_FRIEDRICH', 'MEMENTO_TUBMAN_SIDEARM'),
('LEADER_HARRIET_TUBMAN', 'MEMENTO_TUBMAN_SIDEARM'),
('LEADER_TRUNG_TRAC', 'MEMENTO_TUBMAN_SIDEARM'),
('LEADER_XERXES', 'MEMENTO_TUBMAN_SIDEARM');

-- leader specifics
INSERT INTO LeaderMementoSynergy (LeaderType, MementoType) VALUES
('LEADER_AUGUSTUS', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),
('LEADER_AUGUSTUS', 'MEMENTO_AUGUSTUS_BREASTPLATE'),
('LEADER_AUGUSTUS', 'MEMENTO_AUGUSTUS_CLIPEUS_VIRTUTIS'),

('LEADER_HAPSHETSUT', 'MEMENTO_HATSHEPSUT_ROYAL_MACE'),
('LEADER_HAPSHETSUT', 'MEMENTO_HATSHEPSUT_FALSE_BEARD'),
('LEADER_HAPSHETSUT', 'MEMENTO_HATSHEPSUT_URAEUS'),

('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_BENJAMIN_FRANKLIN_BIFOCALS'),
('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_BENJAMIN_FRANKLIN_KITE'),
('LEADER_BENJAMIN_FRANKLIN', 'MEMENTO_BENJAMIN_FRANKLIN_GLASS_ARMONICA'),

('LEADER_CATHERINE', 'MEMENTO_CATHERINE_EAGLE_BANNER'),
-- ('LEADER_CATHERINE', 'MEMENTO_CATHERINE_POTEMKINS_SWORD_KNOT'),
('LEADER_CATHERINE', 'MEMENTO_CATHERINE_GREAT_IMPERIAL_CROWN'),

('LEADER_CHARLEMAGNE', 'MEMENTO_CHARLEMAGNE_JOYEUSE'),
-- ('LEADER_CHARLEMAGNE', 'MEMENTO_CHARLEMAGNE_GLOBUS_CRUCIGER'),
('LEADER_CHARLEMAGNE', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),

('LEADER_CONFUCIUS', 'MEMENTO_CONFUCIUS_ANALECTS'),
('LEADER_CONFUCIUS', 'MEMENTO_CONFUCIUS_ALTAR_SET'),
('LEADER_CONFUCIUS', 'MEMENTO_CONFUCIUS_BRUSH_SCROLL'),

('LEADER_ASHOKA', 'MEMENTO_ASHOKA_RENOUNCER_CHAKRA'),
('LEADER_ASHOKA', 'MEMENTO_ASHOKA_RENOUNCER_GOLD_SAPPHIRE_FLOWERS'),
('LEADER_ASHOKA', 'MEMENTO_ASHOKA_RENOUNCER_DIAMOND_THRONE'),

('LEADER_FRIEDRICH', 'MEMENTO_FRIEDRICH_OBLIQUE_WALKING_STICK'),
-- ('LEADER_FRIEDRICH', 'MEMENTO_FRIEDRICH_OBLIQUE_ORDER_BLACK_EAGLE'),             -- already granted
-- ('LEADER_FRIEDRICH', 'MEMENTO_FRIEDRICH_OBLIQUE_KRONE_VON_FRIEDRICH'),           -- ai dont do commands, right

('LEADER_HARRIET_TUBMAN', 'MEMENTO_TUBMAN_LANTERN'),
-- ('LEADER_HARRIET_TUBMAN', 'MEMENTO_TUBMAN_SATCHEL'),
-- ('LEADER_HARRIET_TUBMAN', 'MEMENTO_TUBMAN_SIDEARM'),                             -- already granted

('LEADER_AMINA', 'MEMENTO_AMINA_TAKOBA'),
('LEADER_AMINA', 'MEMENTO_AMINA_KWALKWALI'),
('LEADER_AMINA', 'MEMENTO_AMINA_RAWANI'),


('LEADER_HIMIKO', 'MEMENTO_HIMIKO_QUEEN_GOLDEN_SEAL_STONE'),
-- ('LEADER_HIMIKO', 'MEMENTO_HIMIKO_QUEEN_DOTAKU'),         -- science one already granted
('LEADER_HIMIKO', 'MEMENTO_HIMIKO_QUEEN_YASAKANI_NO_MAGATAMA'),

('LEADER_IBN_BATTUTA', 'MEMENTO_BATTUTA_TRAVELLERS_SANDALS'),
('LEADER_IBN_BATTUTA', 'MEMENTO_BATTUTA_MERCHANTS_SADDLE'),
('LEADER_IBN_BATTUTA', 'MEMENTO_BATTUTA_RIHLA'),

('LEADER_ISABELLA', 'MEMENTO_ISABELLA_QUEENS_JEWELRY'),
('LEADER_ISABELLA', 'MEMENTO_ISABELLA_BALLESTILLA'),
('LEADER_ISABELLA', 'MEMENTO_ISABELLA_PADRON_REAL'),

('LEADER_JOSE_RIZAL', 'MEMENTO_RIZAL_FORGET_ME_NOT'),
('LEADER_JOSE_RIZAL', 'MEMENTO_RIZAL_OPHTHALMOSCOPE'),
('LEADER_JOSE_RIZAL', 'MEMENTO_RIZAL_NOLI_ME_TANGERE'),

('LEADER_LAFAYETTE', 'MEMENTO_LAFAYETTE_LETTER_ADRIENNE'),
-- ('LEADER_LAFAYETTE', 'MEMENTO_LAFAYETTE_HERMIONE_MODEL'),                      -- doesnt really suit em
('LEADER_LAFAYETTE', 'MEMENTO_LAFAYETTE_TRICOLOUR_COCKADE'),

('LEADER_MACHIAVELLI', 'MEMENTO_MACHIAVELLI_DISCORSI_SOPRA_LIVIO'),
('LEADER_MACHIAVELLI', 'MEMENTO_MACHIAVELLI_DELL_ARTE_DELLA_GUERRA'),
-- ('LEADER_MACHIAVELLI', 'MEMENTO_MACHIAVELLI_IL_PRINCIPE'),                          -- ai really wont know to use this, also doesnt suit macheveli at all

('LEADER_PACHACUTI', 'MEMENTO_PACHACUTI_TOPAYAURI'),
('LEADER_PACHACUTI', 'MEMENTO_PACHACUTI_ALL_TOQAPU_TUNIC'),                       -- scout increased vision seems rather weak
('LEADER_PACHACUTI', 'MEMENTO_PACHACUTI_MASCAPAYCHA'),

('LEADER_TRUNG_TRAC', 'MEMENTO_TRUNG_KIEM'),
('LEADER_TRUNG_TRAC', 'MEMENTO_TRUNG_ANKUS'),
('LEADER_TRUNG_TRAC', 'MEMENTO_TRUNG_DONG_SON_DRUM'),

('LEADER_XERXES', 'MEMENTO_XERXES_KING_SCYTHIAN_AXE'),
('LEADER_XERXES', 'MEMENTO_XERXES_KING_LOTUS_BLOSSOM'),
('LEADER_XERXES', 'MEMENTO_XERXES_KING_GOLDEN_SCEPTRE');

-- ibn missing wildcard

INSERT INTO CivMementoSynergy(CivilizationType, MementoType) VALUES
('CIVILIZATION_MAURYA', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('CIVILIZATION_PERSIA', 'MEMENTO_FOUNDATION_SLING_BULLET'),
('CIVILIZATION_ROME', 'MEMENTO_FOUNDATION_SLING_BULLET'),

('CIVILIZATION_AKSUM', 'MEMENTO_FOUNDATION_EA_NASIR'),
('CIVILIZATION_EGYPT', 'MEMENTO_FOUNDATION_EA_NASIR'),
('CIVILIZATION_MISSISSIPPIAN', 'MEMENTO_FOUNDATION_EA_NASIR'),
('CIVILIZATION_PERSIA', 'MEMENTO_FOUNDATION_EA_NASIR'),

('CIVILIZATION_GREECE', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('CIVILIZATION_HAN', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),
('CIVILIZATION_MAYA', 'MEMENTO_FOUNDATION_TREATY_OF_KADESH'),

('CIVILIZATION_KHMER', 'MEMENTO_FOUNDATION_GROMA'),
('CIVILIZATION_MISSISSIPPIAN', 'MEMENTO_FOUNDATION_GROMA'),

('CIVILIZATION_AKSUM', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('CIVILIZATION_EGYPT', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('CIVILIZATION_GREECE', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),
('CIVILIZATION_ROME', 'MEMENTO_FOUNDATION_SHAKOKIDOGU'),

('CIVILIZATION_HAN', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('CIVILIZATION_KHMER', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('CIVILIZATION_MAURYA', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),
('CIVILIZATION_MAYA', 'MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM'),

-- buff civs with UUs
('CIVILIZATION_NORMAN', 'MEMENTO_CHARLEMAGNE_JOYEUSE'),
('CIVILIZATION_NORMAN', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),

('CIVILIZATION_MONGOLIA', 'MEMENTO_CHARLEMAGNE_JOYEUSE'),
('CIVILIZATION_MONGOLIA', 'MEMENTO_CHARLEMAGNE_TENCENDUR'),
('CIVILIZATION_MONGOLIA', 'MEMENTO_CATHERINE_POTEMKINS_SWORD_KNOT'),

('CIVILIZATION_CHOLA', 'MEMENTO_LAFAYETTE_HERMIONE_MODEL'),
('CIVILIZATION_MAJAPAHIT', 'MEMENTO_LAFAYETTE_HERMIONE_MODEL'),

('CIVILIZATION_MISSISSIPPIAN', 'MEMENTO_FOUNDATION_AGINCOURT_ARROWHEAD');

-------------------------------------------------

-- bifocals influence diplo

-- unique units with ranged MEMENTO_FOUNDATION_AGINCOURT_ARROWHEAD

-- specialist improving ones


INSERT INTO MementoSetSynergy(MementoTypePrimary, MementoTypeSecondary) VALUES
('MEMENTO_FOUNDATION_SLING_BULLET', 'MEMENTO_FRIEDRICH_OBLIQUE_ORDER_BLACK_EAGLE'),
('MEMENTO_FOUNDATION_TREATY_OF_KADESH', 'MEMENTO_CHARLEMAGNE_GLOBUS_CRUCIGER'),
('MEMENTO_FOUNDATION_GROMA', 'MEMENTO_ASHOKA_RENOUNCER_GOLD_SAPPHIRE_FLOWERS'),
('MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM', 'MEMENTO_HIMIKO_QUEEN_DOTAKU'),
-- non-attribute ones
('MEMENTO_CHARLEMAGNE_JOYEUSE', 'MEMENTO_CHARLEMAGNE_TENCENDUR');


INSERT INTO SpecificMementoCombo(ComboID, LeaderType, CivilizationType, MementoTypePrimary, MementoTypeSecondary) VALUES
('TrungTracRomeLegatus', 'LEADER_TRUNG_TRAC', 'CIVILIZATION_ROME', 'MEMENTO_XERXES_KING_SCYTHIAN_AXE', 'MEMENTO_FOUNDATION_ART_OF_WAR'),

('AminaResourceHoarderGold', 'LEADER_AMINA', NULL, 'MEMENTO_AMINA_KWALKWALI', 'MEMENTO_HATSHEPSUT_ROYAL_MACE'),
('AminaHomeTurf', 'LEADER_AMINA', NULL, 'MEMENTO_AMINA_TAKOBA', 'MEMENTO_FOUNDATION_COLADA_TIZONA'),
('AminaUnpredictableWarriors', 'LEADER_AMINA', NULL, 'MEMENTO_AMINA_RAWANI', 'MEMENTO_TUBMAN_SIDEARM'),
('AshokaRenInfiniteCelebration', 'LEADER_ASHOKA', NULL, 'MEMENTO_ASHOKA_RENOUNCER_DIAMOND_THRONE', 'MEMENTO_RIZAL_OPHTHALMOSCOPE'),
('AugustusWideRome', 'LEADER_AUGUSTUS', NULL, 'MEMENTO_AUGUSTUS_CORONA_CIVICA', 'MEMENTO_AUGUSTUS_CLIPEUS_VIRTUTIS'),
('AugustusRomanTraditions', 'LEADER_AUGUSTUS', 'CIVILIZATION_ROME', 'MEMENTO_AUGUSTUS_CORONA_CIVICA', 'MEMENTO_LAFAYETTE_TRICOLOUR_COCKADE'),

('BennyFrankDiplomat', 'LEADER_BENJAMIN_FRANKLIN', NULL, 'MEMENTO_BENJAMIN_FRANKLIN_BIFOCALS', 'MEMENTO_BENJAMIN_FRANKLIN_GLASS_ARMONICA'),
('BennyFrankScienceIntoInfluence', 'LEADER_BENJAMIN_FRANKLIN', NULL, 'MEMENTO_BENJAMIN_FRANKLIN_BIFOCALS', 'MEMENTO_HIMIKO_QUEEN_GOLDEN_SEAL_STONE'),
('BennyFrankFoundingFather', 'LEADER_BENJAMIN_FRANKLIN', NULL, 'MEMENTO_LAFAYETTE_TRICOLOUR_COCKADE', 'MEMENTO_LAFAYETTE_LETTER_ADRIENNE'),

('CatherineIcyScience', 'LEADER_CATHERINE', NULL, 'MEMENTO_CATHERINE_GREAT_IMPERIAL_CROWN', 'MEMENTO_CATHERINE_EAGLE_BANNER'),
('CatherinePercentBoosts', 'LEADER_CATHERINE', NULL, 'MEMENTO_BENJAMIN_FRANKLIN_GLASS_ARMONICA', 'MEMENTO_HATSHEPSUT_URAEUS'),
('CatherineGreatWorksAndWonders', 'LEADER_CATHERINE', NULL, 'MEMENTO_HATSHEPSUT_FALSE_BEARD', 'MEMENTO_CATHERINE_EAGLE_BANNER'),

-- joyeuse , tencendur covered already in synergies
-- the other two needs ashoka alt and bolivar
-- confucuius covered in synergies, last in xerxes-alt
('ConfuciusGrowthBoost', 'LEADER_CONFUCIUS', NULL, 'MEMENTO_CONFUCIUS_BRUSH_SCROLL', 'MEMENTO_AUGUSTUS_BREASTPLATE'),
-- rest are in napolean-rev
('FriedrichObUnkillableUnits', 'LEADER_FRIEDRICH', NULL, 'MEMENTO_TUBMAN_SIDEARM', 'MEMENTO_FOUNDATION_COLADA_TIZONA'),               -- this would just be good for any military imo

('TubmanFreePopulation', 'LEADER_HARRIET_TUBMAN', NULL, 'MEMENTO_TUBMAN_LANTERN', 'MEMENTO_FOUNDATION_GARUDA_STATUE'),

('HatshepsutWondersOfEgypt', 'LEADER_HATSHEPSUT', NULL, 'MEMENTO_HATSHEPSUT_FALSE_BEARD', 'MEMENTO_HATSHEPSUT_URAEUS'),

('HimikoWaEverybodyLikesMe', 'LEADER_HIMIKO', NULL, 'MEMENTO_BENJAMIN_FRANKLIN_GLASS_ARMONICA', 'MEMENTO_MACHIAVELLI_DISCORSI_SOPRA_LIVIO'),

('IbnSuperScouts', 'LEADER_IBN_BATTUTA', NULL, 'MEMENTO_BATTUTA_MERCHANTS_SADDLE', 'MEMENTO_FOUNDATION_TRAVELS_MARCO_POLO'),
('IbnNavalExploration', 'LEADER_IBN_BATTUTA', NULL, 'MEMENTO_BATTUTA_MERCHANTS_SADDLE', 'MEMENTO_LAFAYETTE_HERMIONE_MODEL'),
-- ('IbnSuperSight', 'LEADER_IBN_BATTUTA', NULL, 'MEMENTO_FOUNDATION_IMAGO_MUNDI', 'MEMENTO_ISABELLA_BALLESTILLA'),                        -- TODO i dont think ai use the vision button, do they?

('IsabellaWonderLust', 'LEADER_ISABELLA', NULL, 'MEMENTO_ISABELLA_QUEENS_JEWELRY', 'MEMENTO_ISABELLA_PADRON_REAL'),
('IsabellaSpanishArmada', 'LEADER_ISABELLA', NULL, 'MEMENTO_LAFAYETTE_HERMIONE_MODEL', 'MEMENTO_ISABELLA_BALLESTILLA'),
('IsabellaSettlerColonies', 'LEADER_ISABELLA', NULL, 'MEMENTO_BATTUTA_MERCHANTS_SADDLE', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),

('JoseGovernmentSnowball', 'LEADER_JOSE_RIZAL', NULL, 'MEMENTO_LAFAYETTE_TRICOLOUR_COCKADE', 'MEMENTO_LAFAYETTE_LETTER_ADRIENNE'),
('JoseInfiniteCelebration', 'LEADER_JOSE_RIZAL', NULL, 'MEMENTO_RIZAL_OPHTHALMOSCOPE', 'MEMENTO_ASHOKA_RENOUNCER_DIAMOND_THRONE'),

('LafayetteFlexibleGovernment', 'LEADER_LAFAYETTE', NULL, 'MEMENTO_LAFAYETTE_TRICOLOUR_COCKADE', 'MEMENTO_FOUNDATION_CORPUS_JURIS_CIVILIS'),
('LafayetteTraditionsSnowball', 'LEADER_LAFAYETTE', NULL, 'MEMENTO_LAFAYETTE_TRICOLOUR_COCKADE', 'MEMENTO_ASHOKA_RENOUNCER_DIAMOND_THRONE'),
('LafayetteToDistantShores', 'LEADER_LAFAYETTE', NULL, 'MEMENTO_BATTUTA_MERCHANTS_SADDLE', 'MEMENTO_AUGUSTUS_CORONA_CIVICA'),                     -- TODO this should be barred fron antiquity, right?

-- machevellis are in napoleon and tecumseh

('PachacutiMountainHomes', 'LEADER_PACHACUTI', NULL, 'MEMENTO_PACHACUTI_MASCAPAYCHA', 'MEMENTO_CONFUCIUS_ALTAR_SET'),               -- TODO couldn't this just be covered by giving those confucius ones as bias to him? or synergy with em
('PachacutiGrowingTall', 'LEADER_PACHACUTI', NULL, 'MEMENTO_PACHACUTI_MASCAPAYCHA', 'MEMENTO_CONFUCIUS_BRUSH_SCROLL'),


('TrungTracStackingScience', 'LEADER_TRUNG_TRAC', NULL, 'MEMENTO_TRUNG_DONG_SON_DRUM', 'MEMENTO_BENJAMIN_FRANKLIN_GLASS_ARMONICA'),

('XerxesKokConqueror', 'LEADER_XERXES', NULL, 'MEMENTO_AUGUSTUS_CORONA_CIVICA', 'MEMENTO_TRUNG_ANKUS'),
('XerxesKokImmortalImmortals', 'LEADER_XERXES', 'CIVILIZATION_PERSIA', 'MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT', 'MEMENTO_TUBMAN_SIDEARM'),
('XerxesKokPersianEmpire', 'LEADER_XERXES', 'CIVILIZATION_PERSIA', 'MEMENTO_AUGUSTUS_CORONA_CIVICA', 'MEMENTO_XERXES_KING_GOLDEN_SCEPTRE');
