INSERT INTO SlthLeaderCivPriorities (CivilizationType, LeaderType, Priority) VALUES
('CIVILIZATION_ROME', 'LEADER_ADA_LOVELACE', 2),
('CIVILIZATION_GREECE', 'LEADER_ADA_LOVELACE', 2),
('CIVILIZATION_NORMAN', 'LEADER_ADA_LOVELACE', 2),
('CIVILIZATION_ABBASID', 'LEADER_ADA_LOVELACE', 1),
('CIVILIZATION_RUSSIA', 'LEADER_ADA_LOVELACE', 1);