INSERT INTO SlthLeaderCivPriorities (CivilizationType, LeaderType, Priority) VALUES
('CIVILIZATION_MAURYA', 'LEADER_ASHOKA_ALT', 4),
('CIVILIZATION_KHMER', 'LEADER_ASHOKA_ALT', 2),
('CIVILIZATION_MISSISSIPPIAN', 'LEADER_HIMIKO_ALT', 2),
('CIVILIZATION_KHMER', 'LEADER_HIMIKO_ALT', 2),
('CIVILIZATION_CHOLA', 'LEADER_ASHOKA_ALT', 3),
('CIVILIZATION_HAWAII', 'LEADER_ASHOKA_ALT', 1),
('CIVILIZATION_HAWAII', 'LEADER_HIMIKO_ALT', 2),
('CIVILIZATION_MAJAPAHIT', 'LEADER_HIMIKO_ALT', 1),
('CIVILIZATION_MUGHAL', 'LEADER_ASHOKA_ALT', 2),
('CIVILIZATION_SIAM', 'LEADER_ASHOKA_ALT', 2),
('CIVILIZATION_MEIJI', 'LEADER_HIMIKO_ALT', 3),
('CIVILIZATION_SIAM', 'LEADER_HIMIKO_ALT', 2);