INSERT INTO SlthLeaderCivPriorities (CivilizationType, LeaderType, Priority) VALUES
('CIVILIZATION_ROME', 'LEADER_BOLIVAR', 2),
('CIVILIZATION_MAYA', 'LEADER_BOLIVAR', 2),
('CIVILIZATION_SPAIN', 'LEADER_BOLIVAR', 2),
('CIVILIZATION_INCA', 'LEADER_BOLIVAR', 2),
('CIVILIZATION_MEXICO', 'LEADER_BOLIVAR', 3),
('CIVILIZATION_FRENCH_EMPIRE', 'LEADER_BOLIVAR', 1);