INSERT INTO SlthLeaderCivPriorities (CivilizationType, LeaderType, Priority) VALUES
('CIVILIZATION_BULGARIA', 'LEADER_CATHERINE', 3),
('CIVILIZATION_BULGARIA', 'LEADER_AUGUSTUS', 2),
('CIVILIZATION_BULGARIA', 'LEADER_CHARLEMAGNE', 1);