INSERT INTO SlthLeaderCivPriorities (CivilizationType, LeaderType, Priority) VALUES
('CIVILIZATION_CARTHAGE', 'LEADER_HATSHEPSUT', 2),
('CIVILIZATION_CARTHAGE', 'LEADER_IBN_BATTUTA', 2),
('CIVILIZATION_CARTHAGE', 'LEADER_ISABELLA', 2),
('CIVILIZATION_CARTHAGE', 'LEADER_AUGUSTUS', 1);