INSERT INTO SlthLeaderCivPriorities (CivilizationType, LeaderType, Priority) VALUES
('CIVILIZATION_ROME', 'LEADER_FRIEDRICH_ALT', 2),
('CIVILIZATION_EGYPT', 'LEADER_FRIEDRICH_ALT', 1),
('CIVILIZATION_PERSIA', 'LEADER_XERXES_ALT', 4),
('CIVILIZATION_MAURYA', 'LEADER_XERXES_ALT', 1),
('CIVILIZATION_NORMAN', 'LEADER_FRIEDRICH_ALT', 1),
('CIVILIZATION_SPAIN', 'LEADER_FRIEDRICH_ALT', 1),
('CIVILIZATION_ABBASID', 'LEADER_XERXES_ALT', 2),
('CIVILIZATION_MONGOLIA', 'LEADER_XERXES_ALT', 2),
('CIVILIZATION_PRUSSIA', 'LEADER_FRIEDRICH_ALT', 4),
('CIVILIZATION_FRENCH_EMPIRE', 'LEADER_FRIEDRICH_ALT', 2),
('CIVILIZATION_MUGHAL', 'LEADER_XERXES_ALT', 2),
('CIVILIZATION_RUSSIA', 'LEADER_XERXES_ALT', 1);